# Generated by Django 5.2.6 on 2025-10-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
