# Generated by Django 5.2.6 on 2025-10-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_alter_userschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquote',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userquote',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userquote',
            name='is_share',
            field=models.BooleanField(default=False),
        ),
    ]
