# Generated by Django 5.2.6 on 2025-10-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('quote', '0003_userquote_is_liked_userquote_is_saved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userschedule',
            name='all_cornjobs',
            field=models.ManyToManyField(to='django_celery_beat.crontabschedule'),
        ),
        migrations.AddField(
            model_name='userschedule',
            name='all_schedule',
            field=models.ManyToManyField(to='django_celery_beat.periodictask'),
        ),
        migrations.AlterField(
            model_name='userschedule',
            name='interval_minutes',
            field=models.IntegerField(default=1),
        ),
    ]
