# Generated by Django 5.2.6 on 2025-10-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_userschedule_all_cornjobs_userschedule_all_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquote',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
