# Generated by Django 5.2.6 on 2025-10-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='SupportFiles')),
            ],
        ),
    ]
