# Generated by Django 5.2.6 on 2025-11-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='apple_original_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='apple_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
