
from django.urls import path
from .views import (
    AdminTokenObtainPairView,
    RevenueReportAPIView,
    DashboardAPIView,
    WeeklyUserQuoteActivityAPIView,
    SubscriptionDistributionAPIView,
    UserListView,
    DeactivateAccountView,
    DeleteAccountView,
    NotificationDetailView,
    NotificationListCreateView,
    BadgeListCreateView,
    BadgeDetailView,
    LeaderboardView,
    DeleteUserFromLeaderboard,
    PaymentListView,
    PaymentDeleteView,
    SubscriptionPlanUpdateView,
    PrivacyPolicyAPIView,
    TrimsAndConditionAPIView,
    PrivacyPolicyRetrieveAPIView,
    TermsAndConditionRetrieveAPIView,
    ActivateAccountView,
    SubscriptionPlanListView,
    ChangeUserSubscription

)

urlpatterns = [
    path('login/', AdminTokenObtainPairView.as_view(), name='admin-login'),
    path('revenue_report/', RevenueReportAPIView.as_view(), name='Revenue Report'),
    path('dashboard_data/', DashboardAPIView.as_view(), name='Dashboard Data'),
    path('weekly_user_activity/', WeeklyUserQuoteActivityAPIView.as_view(), name='Dashboard Data'),
    path('subscription_distribution/', SubscriptionDistributionAPIView.as_view(), name='Subscription Distribution'),
    path('users/', UserListView.as_view(), name='user-list'),
    path('account/deactivate/<int:pk>/', DeactivateAccountView.as_view(), name='deactivate-account'),
    path('account/activate/<int:pk>/', ActivateAccountView.as_view(), name='Activate-account'),
    path('account/delete/<int:pk>/', DeleteAccountView.as_view(), name='delete-account'),
    path('notifications/', NotificationListCreateView.as_view(), name='notification-list-create'),
    path('notifications/<int:pk>/', NotificationDetailView.as_view(), name='notification-detail'),
    path('badges/', BadgeListCreateView.as_view(), name='badge-list-create'),
    path('badges/<int:pk>/', BadgeDetailView.as_view(), name='badge-detail'),
    path('leaderboard/', LeaderboardView.as_view(), name='leaderboard-list'),
    path('leaderboard/<int:pk>/delete/', DeleteUserFromLeaderboard.as_view(), name='delete-user-from-leaderboard'),
    path('payments/', PaymentListView.as_view(), name='payment-list'),
    path('payments/<int:pk>/delete/', PaymentDeleteView.as_view(), name='payment-delete'),
    path('subscription-plan/<str:name>/update/', SubscriptionPlanUpdateView.as_view(), name='subscription-plan-update'),
    path('subscription-plan/list/', SubscriptionPlanListView.as_view(), name='subscription-plan-list'),
    path('admin/privacy-policy/', PrivacyPolicyAPIView.as_view(), name='admin-privacy-policy'),
    path('admin/terms-and-condition/', TrimsAndConditionAPIView.as_view(), name='admin-terms-and-condition'),
    path('privacy-policy/', PrivacyPolicyRetrieveAPIView.as_view(), name='privacy-policy-retrieve'),
    path('terms-and-condition/', TermsAndConditionRetrieveAPIView.as_view(), name='terms-and-condition-retrieve'),
    path('users/subscription/update/',ChangeUserSubscription.as_view(),name='User Subscription View')
]