# Generated by Django 5.2.6 on 2025-10-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField(max_length=500)),
                ('time', models.DateTimeField()),
                ('users', models.CharField(blank=True, choices=[('all_user', 'All_User'), ('free', 'Free'), ('premium', 'Premium')], max_length=255, null=True)),
            ],
        ),
    ]
