# Generated by Django 5.2.6 on 2025-10-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_privacypolicy_tremsandcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='tremsandcondition',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
