# Generated by Django 5.2.6 on 2025-10-16 06:34

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fitness', 'Fitness'), ('career', 'Career'), ('business', 'Business'), ('discipline', 'Discipline'), ('mindset', 'Mindset')], max_length=200, null=True),
        ),
    ]
