# Generated by Django 5.2.6 on 2025-10-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_badge_userbadge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbadge',
            name='points_earned',
        ),
    ]
