# Generated by Django 5.2.6 on 2025-10-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_friendship_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Premium Monthly'), ('yearly', 'Premium Yearly'), ('lifetime', 'Lifetime Premium')], default='free', max_length=20),
        ),
    ]
