# Generated by Django 5.2.6 on 2025-10-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='level_required',
            field=models.IntegerField(default=0),
        ),
    ]
